site_name: Furniture Designs
site_description: Collection of FreeCAD furniture design projects
site_author: Guillermo García
theme:
  name: readthedocs
  locale: en
  highlightjs: true
  hljs_languages:
  - python
  - yaml
plugins:
- search
markdown_extensions:
- tables
- toc:
    permalink: true
- attr_list
- md_in_html
nav:
- Home: index.md
- Bed Columns: bed_columns/index.md
- Coffee Table: coffee_table/index.md
- Coffee Table Small: coffee_table_small/index.md
- Computer Desk: computer_desk/index.md
- Night Stand: night_stand/index.md
- Router Accesories: router_accesories/index.md
- Shared Desk:
  - Shared Desk 02: shared_desk/shared_desk_02.md
  - Shared Desk 02: shared_desk/shared_desk_02.md
- Terrace Bench: terrace_bench/index.md
- Terrace Table: terrace_table/index.md
- Wall Bike Rack: wall_bike_rack/index.md
- Work Bench: work_bench/index.md
